# Generated by Django 4.2.9 on 2024-06-18 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_city_post_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='location',
            new_name='position',
        ),
    ]
