# Generated by Django 4.2.9 on 2024-07-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_socialmedialink_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
    ]
