# Generated by Django 5.1 on 2024-09-03 00:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='nobody_image_wcjcx2', max_length=255, verbose_name='image'),
        ),
    ]
