# Generated by Django 4.2.9 on 2024-09-03 14:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='nobody_image_ij7rzz', max_length=255, verbose_name='image'),
        ),
    ]
