# Generated by Django 4.2.9 on 2024-09-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../nobody_image_tyus4w', upload_to='images/'),
        ),
    ]
