image:
  file: .gitpod.dockerfile
tasks:
  - name: Setup Environment
    command: |
      pip install -r requirements.txt
vscode:
  extensions:
    - ms-python.debugpy
    - PKief.material-icon-theme
    - charliermarsh.ruff
    - ms-python.python
    - esbenp.prettier-vscode
    - christian-kohler.path-intellisense
    - yzhang.markdown-all-in-one
    - GitHub.github-vscode-theme
