[tool.djlint]
ignore = "ALL"
profile = "django"
indent = 2
max_line_length = 80
use_gitignore = true
format_css = true
format_js = true
max_attribute_length = 80
max_blank_lines = 1
format_attribute_template_tags = true
line_break_after_multiline_tag = true
preserve_blank_lines = true

[tool.djlint.per-file-ignores]
"**/templates/**/*.html" = ["H006"]

[tool.ruff]
exclude = [
    ".direnv",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "build",
    "dist",
    "env.py",
    "manage.py",
    "media",
    "migrations",
    "node_modules",
    "site-packages",
    "static",
    "templates",
    "venv",
]
line-length = 79
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
ignore = [
    "Q000",
    "Q001",
    "Q003",
]
select = [
    "E4",
    "E7",
    "E9",
    "F",
    "DJ",
    "Q",
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"

[tool.ruff.lint.per-file-ignores]
"settings.py" = [
    "F401",
    "F403",
    "F405",
]
"tests.py" = ["F401"]

[tool.ruff.format]
quote-style = "single"
